### ISSUE TITLE
Dataset on Hugging Face

### ISSUE THREAD

**Issue by katielink** [wshi83/EhrAgent#1]
Hi! This is awesome work! It would very cool to have the dataset on the Hugging Face Hub for greater accessibility for the community. Here are some pointers from the docs: https://huggingface.co/docs/hub/datasets-adding
Let me know if I can answer any questions or provide guidance!

**Comment by wshi83** [comment]
Thank you for your valuable suggestions! Hugging face hub is a great platform for open-source data sharing. We are working on uploading our preprocessed data to Hugging face. We will send an update message once uploaded.

**Comment by wshi83** [comment]
Hi, below please find our preprocessed data on Huggingface:

- [EHRAgnet-MIMIC-III](https://huggingface.co/datasets/wshi83/EHRAgent-mimic_iii)
- [EHRAgnet-eICU](https://huggingface.co/datasets/wshi83/EHRAgent-eicu)
- [EHRAgent-TREQS](https://huggingface.co/datasets/wshi83/EHRAgent-treqs)

Please let me know if you have any further questions or suggestions!
